### ISSUE TITLE
JavaScript is unusable.

### ISSUE THREAD

**Issue by xekoukou** [sustrik/ribosome#10]
At the moment, the JavaScript version seem unusable.

**Comment by sustrik** [comment]
Is this node vs. nodejs problem or something different?

**Comment by xekoukou** [comment]
The unlink(delete) was moved.

For me (debian), node vs nodejs is not a problem because I can always install the nodejs-legacy package. I haven't checked other distributions but I have the impression only debian used nodejs.

**Comment by sustrik** [comment]
Aha. I've added the unlink to the beginning of the processing because when the tool was run while the previous version of RNA file existed, it just appended the new stuff to the existing file, rather than creating a new one.

What exact error are you seeing?

**Comment by xekoukou** [comment]
I think that my version is a bit different and it deletes the file after it is executed.

**Comment by sustrik** [comment]
Yes, I should uncomment that line. But still: If .rna script is present (maybe because the previous run of the tool was done with --rna flag) the next run will append to it, rather than replace it.

I am not a JavaScript programmer -- would you mind suggesting how to fix that?

**Comment by sustrik** [comment]
For now, I've put the unlink to the end. It should solve the problem you are reporting, but the one with appending to previosuly generated rna files persists...

**Comment by xekoukou** [comment]
It was a simple problem but I didn't have the time to look at it.

**Comment by sustrik** [comment]
Should be fully fixed now. Please, do close the issue if you are OK with it.
