### ISSUE TITLE
Will you accept a PR for a Python implementation

### ISSUE THREAD

**Issue by alixedi** [sustrik/ribosome#13]
I have implemented ribosome in Python.

It passes all the tests but I am testing some more.

Will you accept a PR for this?

**Comment by sustrik** [comment]
I definitely will, but I think it's not doable. Actually my first try was to do it in Python, but there's the problem of semantically-relevant indentation in Python. Consider this case:

    .{
    if x > 0:
        x = 1
    .    foo
    .}

Is the foo line part of the conditional code? Or is it just an unconditional footer? There's no way to say.

Ideas?

**Comment by sustrik** [comment]
Unless an explicit pass statement would be required in such cases...

    .{
    if x > 0:
        x = 1
    .    foo
        pass
    .}

**Comment by alixedi** [comment]
I ran into this first thing :)

I solved this by making the indentation semantically relevant in the `dna`. So for instance:

    x = 0
    .{
    if x > 0:
        x = 1
    .    foo
    .}

would produce:

    {
        foo
    }

On the other hand:

    x = 0
    .{
    if x > 0:
        x = 1
        .foo
    .}

would produce:

    {
    }

The implementation is also reasonably elegant - as soon as I get my hands on a line, I extract the white-space to the left and right of the text and put it in the fridge:

    lspace = line.replace(line.lstrip(), '')
    rspace = line.replace(line.rstrip(), '')

The line is processed exactly as before except when we are to write it:

    rnawrite('''Block.add('%s', locals()%s''' % (lspace, line, rspace))

What do you think?

**Comment by sustrik** [comment]
The problem with this approach is that if you have a long dna script and look only at the destination part of it (e.g. by colouring it appropriately in vim), it will be terribly misaligned:

                       .if (c == 0) {
        .    if (a == b) {
                    .        a = 0;
.    }
                                     .{

And such. Soon you won't be able to follow the code.

What I would like to see instead is:

.if (c == 0) {
.    if (a == b) {
.        a = 0;
.    }
.{

The "pass" approach may actually work and is reasonable easy to implement: Just keep track of the indenting of the last control-language line and apply the same amount of indentation to all the subsequently following destination-language lines.

Thoughts?

**Comment by alixedi** [comment]
One possible corner case where the `pass` approach will get into trouble will be:

    .{
    if x > 0:
    .    foo
    .}

If are keeping track of the last control-language indentation, this will produce Python with syntax errors.

Also, I think we will do well to stop the presentation constraints (how the destination code reads without the control code) from having too much influence on the `dna` syntax.

There may be a more elegant solution to the presentation problem - for instance, vim may consider a mock purge of the pre `.` white-space if asked nicely - a special mode to view destination code perhaps?

**Comment by sustrik** [comment]
True. pass thing isn't sufficient to do the job.

Still, solving the indentation hell cleanly is a sine qua non for a decent code generation tool. When maintaining a large code-generated codebase (especially if there are multiple generation steps) keeping the indentation clean is not a matter of convenience, but rather of survival.

For now, I would suggest that you just go on with indented dot-lines and the meantime we can try to figure out how to do that cleanly.

Looking at other python-based code generation tools (e.g. http://www.makotemplates.org/ or jinja) it looks like they are introducting "end" statements to deal with the problem. (Ugly!)

Maybe some kind of explicit indenting commands? Hm.
