### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by alixedi** [sustrik/ribosome#14]
Specifically, `nested` fails with Ruby 1.9.3. Here is what you can do to recreate the issue:

1. Create the `.rna` file:

    $ ruby ../ribosome.rb --rna nested.rb.dna > nested.rb.rna

2. Try and run the `.rna` file:

    $ ruby nested.rb.rna
    nested.rb.rna:225:in `add': undefined method `-' for "1":String (NoMethodError)
        from nested.rb.rna:280:in `dot'
        from nested.rb.rna:342:in `<main>'

3. the problem seems to stem from (surprise-surprise) type coercion. Specifically:

        level = line[j] - ?0

I am no expert in Ruby, but google tells me there is substantial disagreement between various Ruby versions on how to go about doing this.

**Comment by sustrik** [comment]
A-ha. Thanks for reporting the problem. I'll have a look at it later on.

**Comment by sustrik** [comment]
Fixed.
