### ISSUE TITLE
Exception in ribosome.js

### ISSUE THREAD

**Issue by sustrik** [sustrik/ribosome#25]
I'm getting this exception when using ribosome with nodejs v0.6.12:

```
$ ../ribosome.js embedded.js.dna 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'appendFileSync'
    at rnawrite (/home/sustrik/ribosome/ribosome.js:432:12)
    at Object.<anonymous> (/home/sustrik/ribosome/ribosome.js:476:1)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:41)
```

**Comment by xekoukou** [comment]
It was added in nodejs 0.8.0 .

https://github.com/joyent/node/wiki/API-changes-between-v0.6-and-v0.8

**Comment by xekoukou** [comment]
By the way, the rethrow function needs some work which I didn't have the
time to do. It needs to parse the error message correctly.

**Comment by sustrik** [comment]
I see. There weren't a method to write to a file before that?

As for the rethrow, feel free to disable it for now. Reporting line numbers from RNA file may not be extra-convenient, but it'll do temporarily.

**Comment by xekoukou** [comment]
Probably, one could find a solution. Nodejs most of the time has
asynchronous callback interfaces, unfortunately.

About rethrow, I just need to find the nodejs error format to parse it
correctly. Right now, it omits some helpful error messages. Will fix this
in the future.
