### ISSUE TITLE
The dollar at the end doesn't make ribosome remove the whitespace at the end

### ISSUE THREAD

**Issue by xekoukou** [sustrik/ribosome#36]
The test is wrong since there is no whitespace in the end.

Both ribosome.js and ribosome.rb fail to remove it.

**Comment by sustrik** [comment]
Dollar should preserve the space. It's only used as a readability improvement, so that whitespace in the source is clearly visible:

```
.abc $
.def
```

Am I misunderstanding you?

**Comment by xekoukou** [comment]
If that is so, then the implementations are correct. Closing the issue.
