### ISSUE TITLE
Python ribosome cannot handle empty variables

### ISSUE THREAD

**Issue by KerstinKeller** [sustrik/ribosome#51]
It seems that ribosome.py cannot handle empty string variables for output generation.
E.g.

    var = ""
    .Hello @{var}!

I expect that it would output

    Hello !

but the output file is empty.

On the other hand

    var = "World"
    .Hello @{var}!

correctly outputs

    Hello World!

**Comment by KerstinKeller** [comment]
It seems to me, that ribosome.py is missing a `return` statement on line 116 in the function `trim`.

**Comment by sustrik** [comment]
Correct. Would you like to send a pull  request?

**Comment by sustrik** [comment]
Fixed.
