### ISSUE TITLE
Document that if ribosome Python scripts are written for Python 3, then Ribosome itself must be called with Python 3

### ISSUE THREAD

**Issue by JesseTG** [sustrik/ribosome#56]
I discovered this on my own.  If your `.py.dna` scripts are for Python 3, you must run Ribosome itself with Python 3.

**Comment by sustrik** [comment]
Feel free to send a pull request. The docs are here: https://github.com/sustrik/ribosome/tree/gh-pages

**Comment by JesseTG** [comment]
Of course.
