### ISSUE TITLE
set syntax=off in ribosome.vim

### ISSUE THREAD

**Issue by xekoukou** [sustrik/ribosome#8]
All functions should have this because for some reason after you set the syntax, manual highlighting non dot lines doesn't work for some lines.
```
function JsView ()
    unlet b:current_syntax
    set syntax=off
    set syntax=javascript
    syn match dot "^\..*$"

```

By the way, I have translated ribosome into javascript.

**Comment by sustrik** [comment]
Hey, nice! Where's the project?

(I am not really familiar with VimL, but I'll just steal what you have there.)

**Comment by xekoukou** [comment]
Here it is: [protein](https://github.com/xekoukou/protein)

I am not good at VimL either.

**Comment by sustrik** [comment]
Want me to link it from ribosome README?

**Comment by xekoukou** [comment]
I ll copy the documentation from your readme if you don't mind.

You can link it from ribosome.

**Comment by sustrik** [comment]
Sure, use the docs at will, you'll have to translate the examples though.

**Comment by xekoukou** [comment]
So to close this issue, If @sustrik agrees, we need to use vim files for multiple languages.Please use the javascript vim file from protein that has some changes: https://github.com/xekoukou/protein/blob/master/protein.vim

We just need to call them ribosome.js.vim
                                         ribosome.rb.vim

**Comment by sustrik** [comment]
I was thinking of joining all the vims into a single one and providing a command to switch between languages.

**Comment by xekoukou** [comment]
wouldn't it be better if vim got the correct language with the suffix?

**Comment by sustrik** [comment]
Yes. Any idea how to do that?

**Comment by sustrik** [comment]
The original issue is fixed now. Closing the ticket.
